version: '2'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - '3306:3306'
  elixir:
    build: .
    volumes:
      - .:/var/opt/app
    depends_on:
      - mysql
    ports:
      - "4000:4000"
    command: bash -c "mix deps.get && mix phoenix.server"