version: '2'
services:
  storage:
    image: busybox
    volumes:
      - /var/lib/mysql
  mysql:
    image: mysql
    environment:
      - "TZ=Japan"
    networks:
      - default
    ports:
      - '3306:3306'
  elixir:
    image: h3poteto/phoenix
    volumes:
      - .:/var/opt/app
    depends_on:
      - mysql
    ports:
      - "4000:4000"
    command: mix phoenix.server
